// Generated by scripts/generate_diagnostic_contract.py. DO NOT EDIT.
// Edit Packages/ThreadingRemoteKit/Contracts/RemoteDiagnosticContract.json instead.

import Foundation

/// The content-free event vocabulary accepted by native diagnostics and the public intake.
public enum RemoteDiagnosticEvent: String, Codable, CaseIterable, Hashable, Sendable {
    case appLaunched
    case appBecameActive
    case hostPairingStarted
    case hostPairingSucceeded
    case hostPairingFailed
    case hostRemoved
    /// One catalogue refresh began. trace joins its route attempts and final result.
    case hostRefreshStarted
    case hostRefreshSucceeded
    case hostRefreshFailed
    /// One bounded way into a host began. This is a lifecycle record, never a request log.
    case hostRouteStarted
    /// One coarse, bounded stage inside an already-started route attempt.
    case hostRouteProgress
    case hostRouteEnded
    case hostListenerStarted
    case hostListenerFailed
    /// One door of the host listener set started answering on its addresses.
    case hostDoorBound
    /// One enabled door has nothing listening for it. The reason field says why.
    case hostDoorUnreachable
    /// The Mac minted the identity its listeners present. detail carries only a short fingerprint
    /// hash.
    case hostIdentityCreated
    /// The listener identity was replaced, unpairing devices without a rotation announcement.
    case hostIdentityReset
    /// A prepared successor identity became the identity the listeners present.
    case hostIdentityRotated
    /// The Mac began advertising its listener; origin is a hash, never an address or instance name.
    case hostDiscoveryRegistered
    case hostDiscoveryWithdrawn
    /// A client saw a Threading service; peer is a pseudonym and no address or instance name is
    /// recorded.
    case hostDiscoveryFound
    case hostDiscoveryMatched
    case hostDiscoveryIgnored
    case relayConnected
    case relayFailed
    case authenticationRefused
    case socketConnecting
    case socketConnected
    /// The host finished attaching one socket to a session or terminal: hello sent, bounded replay
    /// handed to the connection. durationMS is the host-side attach cost; kind is session or
    /// terminal.
    case terminalAttachEnded
    /// The host ended one session terminal's resize hydration: the hold between a phone's first
    /// grid and its terminalReady boundary. durationMS is the hold, reason is quiet,
    /// firstOutputTimeout, ceiling, noResize or cancelled, total counts the output bursts seen
    /// during it, and detail names the agent runtime.
    case terminalHydrationEnded
    case socketEnded
    case socketFailed
    /// A failed live socket scheduled one bounded exponential retry.
    case socketReconnectScheduled
    /// A parked authenticated session socket began reattaching to its live surface.
    case sessionResumeStarted
    /// A parked session reattach reached a terminal result with its own duration, separate from
    /// socket age.
    case sessionResumeEnded
    /// A person opened one chat. trace joins its progress and result; detail names the agent
    /// runtime.
    case sessionOpenStarted
    /// One fixed stage of a chat opening (catalogue, wake, socket, hello) was reached. durationMS
    /// is cumulative from the tap.
    case sessionOpenProgress
    /// A chat opening became usable, failed or was abandoned. durationMS is tap to usable; reason
    /// says whether it was pooled, fresh or woken; phase names how the surface was revealed.
    case sessionOpenEnded
    /// A content-free prompt or atomic terminal submission began.
    case promptSubmissionStarted
    /// A prompt or atomic terminal submission reached an acknowledgement or terminal failure.
    case promptSubmissionEnded
    /// One rate-limited direct-terminal input latency probe began; it contains no input bytes.
    case terminalInputProbeStarted
    /// A sampled direct-terminal input reached host admission or timed out.
    case terminalInputProbeEnded
    /// A sampled printable key began expected-cursor-cell observation; no characters or coordinates
    /// are retained in diagnostics.
    case terminalInputVisualProbeStarted
    /// Cumulative keypress timing at send, first output, matched cell parse, or actual matched cell
    /// draw. First output is not necessarily an echo.
    case terminalInputVisualProbeProgress
    /// A matched draw reached an estimated display opportunity, or observation ended without a
    /// match. This is not physical scanout measurement.
    case terminalInputVisualProbeEnded
    case permissionDecisionSent
    case permissionDecisionReceived
    case notificationAuthorization
    case apnsRegistrationSucceeded
    case apnsRegistrationFailed
    case notificationRegistrationStarted
    case notificationRegistrationSucceeded
    case notificationRegistrationFailed
    case notificationRegistrationReceived
    case notificationReceived
    case notificationSuppressed
    case notificationPresented
    case notificationOpened
    /// A content-free host delivery decision. phase carries the closed transition name.
    case notificationDeliveryTransition
    case notificationRetractionReceived
    case notificationLocallyCleared
    case pushProviderAccepted
    case pushProviderRefused
    case issueReportOpened
    case issueReportExported
    case issueReportSubmissionStarted
    case issueReportSubmissionSucceeded
    case issueReportSubmissionDeferred
    case issueReportSubmissionFailed
    /// A phone attachment preview attempt reached a terminal failure. kind and code remain
    /// structural tokens.
    case attachmentPreviewFailed
    case uncleanExitDetected
    case recoveryModeEntered
    case diagnosticSharingStarted
    case diagnosticSharingStopped
    case diagnosticUploadReceived

    private static let iOSClientUploadEvents: Set<Self> = [
        .appLaunched, .appBecameActive, .hostPairingStarted, .hostPairingSucceeded,
        .hostPairingFailed, .hostRemoved, .hostRefreshStarted, .hostRefreshSucceeded,
        .hostRefreshFailed, .hostRouteStarted, .hostRouteProgress, .hostRouteEnded,
        .hostDiscoveryFound, .hostDiscoveryMatched, .hostDiscoveryIgnored, .socketConnecting,
        .socketConnected, .socketEnded, .socketFailed, .socketReconnectScheduled,
        .sessionResumeStarted, .sessionResumeEnded, .sessionOpenStarted, .sessionOpenProgress,
        .sessionOpenEnded, .promptSubmissionStarted, .promptSubmissionEnded,
        .terminalInputProbeStarted, .terminalInputProbeEnded, .terminalInputVisualProbeStarted,
        .terminalInputVisualProbeProgress, .terminalInputVisualProbeEnded,
        .permissionDecisionSent, .notificationAuthorization, .apnsRegistrationSucceeded,
        .apnsRegistrationFailed, .notificationRegistrationStarted,
        .notificationRegistrationSucceeded, .notificationRegistrationFailed,
        .notificationReceived, .notificationSuppressed, .notificationPresented,
        .notificationOpened, .notificationRetractionReceived, .notificationLocallyCleared,
        .issueReportOpened, .issueReportExported, .issueReportSubmissionStarted,
        .issueReportSubmissionSucceeded, .issueReportSubmissionDeferred,
        .issueReportSubmissionFailed, .attachmentPreviewFailed, .diagnosticSharingStarted,
        .diagnosticSharingStopped
    ]

    private static let browserClientUploadEvents: Set<Self> = [
        .appLaunched, .hostPairingStarted, .hostPairingSucceeded, .hostPairingFailed,
        .hostRefreshStarted, .hostRefreshSucceeded, .hostRefreshFailed, .hostRouteStarted,
        .hostRouteProgress, .hostRouteEnded, .socketConnecting, .socketConnected, .socketEnded,
        .socketFailed, .socketReconnectScheduled, .diagnosticSharingStarted,
        .diagnosticSharingStopped
    ]

    public func allowsClientUpload(from source: RemoteDiagnosticSource) -> Bool {
        switch source {
        case .iOSClient: Self.iOSClientUploadEvents.contains(self)
        case .browserClient: Self.browserClientUploadEvents.contains(self)
        case .macOSHost: false
        }
    }
}

public enum RemoteDiagnosticFieldValidation: String, Codable, Hashable, Sendable {
    case originDigest
    case peerPseudonym
    case sessionPseudonym
    case token
    case unsignedInteger
}

/// Safe structural field names. Their value policy is generated from the same contract.
public enum RemoteDiagnosticField: String, CaseIterable, Hashable, Sendable {
    case trace
    case providerTrace
    case host
    case peer
    case participant
    case session
    case kind
    case transport
    case result
    case code
    case status
    case environment
    case protocolVersion
    case minimumProtocolVersion
    case capability
    case surface
    case enabledKindCount
    case recordCount
    /// A fixed stage such as refresh, prepare, request, hello, or backoff.
    case phase
    case durationMS
    case timeoutMS
    case delayMS
    case generation
    case queueSize
    case previewPresent
    case previewBytes
    case activitySource
    /// The coarse URL-loading phase reached by one bounded request.
    case networkStage
    case dnsMS
    case tcpMS
    case tlsMS
    case serverWaitMS
    case responseMS
    /// A fixed URLSession protocol token, never an address or URL.
    case networkProtocol
    /// A fixed URLSession path token, never an interface name or URL.
    case networkPath
    case connectionReused
    case attempt
    case total
    /// The fixed pass of a bounded walk, such as route, address, or port.
    case wave
    case reason
    /// A truncated address hash: origin- followed by twelve lowercase hexadecimal digits.
    case origin
    /// A bounded machine token qualifying code or reason; never prose or a path.
    case detail

    public var validation: RemoteDiagnosticFieldValidation {
        switch self {
        case .origin: .originDigest
        case .host, .peer, .participant: .peerPseudonym
        case .session: .sessionPseudonym
        case .trace, .providerTrace, .kind, .transport, .result, .code, .status, .environment, .capability, .surface, .phase, .previewPresent, .activitySource, .networkStage, .networkProtocol, .networkPath, .connectionReused, .wave, .reason, .detail: .token
        case .protocolVersion, .minimumProtocolVersion, .enabledKindCount, .recordCount, .durationMS, .timeoutMS, .delayMS, .generation, .queueSize, .previewBytes, .dnsMS, .tcpMS, .tlsMS, .serverWaitMS, .responseMS, .attempt, .total: .unsignedInteger
        }
    }
}

/// Optional, explicitly consented report context with generated platform scope.
public enum RemoteDiagnosticExtraField: String, CaseIterable, Hashable, Sendable {
    case deviceModel
    case interfaceIdiom
    case locale
    case preferredLanguage
    case timeZone
    case lowPowerMode
    case thermalState
    case physicalMemoryMB
    case availableStorageMB
    case displayPoints
    case displayScale
    case applicationState
    case connectionState
    /// A bounded ring of connection-state transitions behind the snapshot state.
    case connectionStateHistory
    /// A bounded ring of attachment-preview attempt outcomes using closed kind and outcome tokens.
    case attachmentPreviewHistory
    /// The warm session-connection pool's counters since their last reset, as closed key.value
    /// tokens.
    case connectionPoolMetrics
    case pairedHostCount
    case visibleSessionCount
    case activeScope
    case activeCapability
    case notificationAuthorization
    case notificationDelivery
    case accessibilityAuthorization
    case screenRecordingAuthorization
    case remoteAccessEnabled
    case appThemeID
    case projectCount
    case sessionCount
    case extensionCount
    case extensionCompanionCount
    case agentAccountSummary
    case previousLaunchClean
    case automaticUpdateChecks
    case simulatorStreaming
    case crashLoopDecision
    case launchLedger
    case lastStartupCheckpoint
    case metricKitDiagnostics
    case metricKitWindow
    case metricKitLastCrash
    case mainThreadStalls

    private static let iOSClientReportFields: Set<Self> = [
        .deviceModel, .interfaceIdiom, .locale, .preferredLanguage, .timeZone, .lowPowerMode,
        .thermalState, .physicalMemoryMB, .availableStorageMB, .displayPoints, .displayScale,
        .applicationState, .connectionState, .connectionStateHistory,
        .attachmentPreviewHistory, .connectionPoolMetrics, .pairedHostCount,
        .visibleSessionCount, .activeScope, .activeCapability, .notificationAuthorization,
        .notificationDelivery
    ]

    private static let macOSHostReportFields: Set<Self> = [
        .notificationAuthorization, .accessibilityAuthorization, .screenRecordingAuthorization,
        .remoteAccessEnabled, .appThemeID, .projectCount, .sessionCount, .extensionCount,
        .extensionCompanionCount, .agentAccountSummary, .previousLaunchClean,
        .automaticUpdateChecks, .simulatorStreaming, .crashLoopDecision, .launchLedger,
        .lastStartupCheckpoint, .metricKitDiagnostics, .metricKitWindow, .metricKitLastCrash,
        .mainThreadStalls
    ]

    public func allowsReportSource(_ source: RemoteDiagnosticSource) -> Bool {
        switch source {
        case .iOSClient: Self.iOSClientReportFields.contains(self)
        case .macOSHost: Self.macOSHostReportFields.contains(self)
        case .browserClient: false
        }
    }
}

public enum RemoteDiagnosticContract {
    public static let schemaVersion = 1
    public static let fingerprint = "a70d957f85bedb3e09de96e6f6ebccfb1319b5f55fac6ced195a609e5dc7bc5c"
}
