import AppKit
import CoreText
import Darwin
import Foundation
import Security
import ThreadingExtensionKit

/// A validated extension directory, inspected without executing extension code.
struct ThreadingExtensionBundle: Equatable {
    let rootURL: URL
    let executableURL: URL
    let sourceURL: URL?
    let manifest: ExtensionManifest
    let companions: [ThreadingExtensionCompanionBundle]
    let themes: [ThreadingExtensionThemeDocument]
    let fonts: [ThreadingExtensionFontFile]
    let localizations: [ThreadingExtensionLocalizationCatalog]

    init(
        rootURL: URL,
        executableURL: URL,
        sourceURL: URL?,
        manifest: ExtensionManifest,
        companions: [ThreadingExtensionCompanionBundle] = [],
        themes: [ThreadingExtensionThemeDocument] = [],
        fonts: [ThreadingExtensionFontFile] = [],
        localizations: [ThreadingExtensionLocalizationCatalog] = []
    ) {
        self.rootURL = rootURL
        self.executableURL = executableURL
        self.sourceURL = sourceURL
        self.manifest = manifest
        self.companions = companions
        self.themes = themes
        self.fonts = fonts
        self.localizations = localizations
    }

    /// The same bundle carrying freshly re-inspected theme documents — the one field live
    /// reload may replace. Everything code-bearing (executable, companions, their signatures)
    /// deliberately keeps the values install validated.
    func replacingThemes(_ themes: [ThreadingExtensionThemeDocument]) -> ThreadingExtensionBundle {
        ThreadingExtensionBundle(
            rootURL: rootURL,
            executableURL: executableURL,
            sourceURL: sourceURL,
            manifest: manifest,
            companions: companions,
            themes: themes,
            fonts: fonts,
            localizations: localizations
        )
    }
}

/// One font file confirmed parseable at inspection time, with the families it carries — read
/// from the file rather than declared, so the install disclosure names what registration will
/// actually make available.
struct ThreadingExtensionFontFile: Equatable {
    let url: URL
    let familyNames: [String]
}

/// One bounded, statically inspected extension translation table.
struct ThreadingExtensionLocalizationCatalog: Equatable {
    let language: String
    let strings: [String: String]
}

/// One theme document read and validated at inspection time. No code has run to produce this.
///
/// The theme's id is already namespaced under the extension identifier
/// (`ext.<identifier>.<contribution id>`), so two packages both shipping a `storm` cannot
/// collide in the library, and a document that states its own id does not get to impersonate
/// a stock or custom theme.
struct ThreadingExtensionThemeDocument: Equatable {
    let contributionID: String
    let theme: AppTheme
    /// The declared app-icon mark, decoded and re-encoded as PNG at inspection time.
    ///
    /// Held as bytes rather than an `NSImage` so the document stays `Equatable` and the
    /// registry's wholesale diff keeps working: two inspections of the same package have to
    /// compare equal, and image objects do not.
    let iconMark: Data?

    /// The sidebar images the theme document's own `sidebar` blocks reference, keyed by the
    /// package-relative name as written, decode-gated and re-encoded like the mark. Empty for
    /// the many themes that state no sidebar dressing.
    let sidebarAssets: [String: Data]

    /// Defaulted, so the many fixtures that care only about a theme document do not each have
    /// to say they ship no artwork.
    init(
        contributionID: String,
        theme: AppTheme,
        iconMark: Data? = nil,
        sidebarAssets: [String: Data] = [:]
    ) {
        self.contributionID = contributionID
        self.theme = theme
        self.iconMark = iconMark
        self.sidebarAssets = sidebarAssets
    }
}

/// One statically inspected nested companion. No code has run to produce this value.
struct ThreadingExtensionCompanionBundle: Equatable {
    let declaration: ExtensionCompanion
    let bundleURL: URL
    let executableURL: URL
    let bundleIdentifier: String
    let signedEntitlements: Set<String>
    /// The requirement generated by the nested app's signature at package inspection time.
    ///
    /// Launch re-validates the current bytes against this exact requirement. For a normal
    /// Developer ID build it binds the worker to its author; for an ad-hoc development build it
    /// pins the exact code directory instead of treating the shared bundle identifier as trust.
    let designatedRequirementData: Data
    let signingTeamIdentifier: String?
}

enum ExtensionBundleError: LocalizedError {
    case manifestTooLarge(maximum: Int)
    case manifestUnreadable(String)
    case manifestInvalid(String)
    case manifestFormatUnsupported(found: Int, supported: Int)
    case unsupportedCapabilities([String])
    case unsupportedCompanionCapabilities([String])
    case executableEscapesBundle
    case executableMissing(String)
    case executableNotRunnable(String)
    case webAssemblyModuleInvalid(String)
    case editableSourceInvalid(String)
    case themeResourceInvalid(path: String, message: String)
    case fontResourceInvalid(path: String, message: String)
    case localizationResourceInvalid(path: String, message: String)
    case companionInvalid(id: String, message: String)
    case launchFailed(String)
    case timedOut
    case outputTooLarge(maximum: Int)
    case processFailed(status: Int32, message: String)
    case invalidRegistration(String)

    var errorDescription: String? {
        switch self {
        case .manifestTooLarge(let maximum):
            return "The extension manifest is larger than \(maximum) bytes."
        case .manifestUnreadable(let message):
            return "The extension manifest could not be read: \(message)"
        case .manifestInvalid(let message):
            return "The extension manifest is invalid: \(message)"
        case .manifestFormatUnsupported(let found, let supported):
            // Which direction matters to the user: one is "update Threading", the other is
            // "this package predates anything this build can run". "Could not be read" — what
            // this used to say — sends people looking for a typo in a file that is fine.
            return found > supported
                ? "This extension needs a newer version of Threading: it uses manifest format "
                    + "\(found) and this build understands \(supported)."
                : "This extension uses manifest format \(found), which this build of Threading "
                    + "no longer supports (it understands \(supported))."
        case .unsupportedCapabilities(let names):
            return "The extension requests unsupported capabilities: \(names.joined(separator: ", "))."
        case .unsupportedCompanionCapabilities(let names):
            return "The extension's companions request unsupported capabilities: "
                + names.joined(separator: ", ") + "."
        case .executableEscapesBundle:
            return "The extension executable resolves outside its extension directory."
        case .executableMissing(let path):
            return "The extension executable does not exist at \(path)."
        case .executableNotRunnable(let path):
            return "The extension executable is not a runnable file at \(path)."
        case .webAssemblyModuleInvalid(let path):
            return "The extension's WebAssembly module is invalid at \(path)."
        case .editableSourceInvalid(let message):
            return "The extension does not contain rebuildable Swift source: \(message)"
        case .themeResourceInvalid(let path, let message):
            return "The extension theme at \(path) is invalid: \(message)"
        case .fontResourceInvalid(let path, let message):
            return "The extension font at \(path) is invalid: \(message)"
        case .localizationResourceInvalid(let path, let message):
            return "The extension localization at \(path) is invalid: \(message)"
        case .companionInvalid(let id, let message):
            return "Companion “\(id)” is invalid: \(message)"
        case .launchFailed(let message):
            return "The extension could not be started: \(message)"
        case .timedOut:
            return "The extension took too long to register."
        case .outputTooLarge(let maximum):
            return "The extension registration exceeded \(maximum) bytes."
        case .processFailed(let status, let message):
            let detail = message.isEmpty ? "No diagnostic was written." : message
            return "The extension exited with status \(status): \(detail)"
        case .invalidRegistration(let message):
            return "The extension returned an invalid registration: \(message)"
        }
    }
}

/// Manifest-first discovery for the initial safe-extension experiment.
///
/// Resolving the executable before launch is deliberate. A relative manifest path is not enough:
/// a symlink inside the bundle could still point at an arbitrary program elsewhere on disk.
enum ExtensionBundleInspector {
    static let manifestName = "threading-extension.json"
    /// Static settings, service schemas, and component metadata can be substantial while still
    /// remaining tiny beside the 256 MiB package cap.
    static let maximumManifestBytes = 256 * 1024
    static let maximumCompanionInfoBytes = 1024 * 1024
    static let supportedCapabilities: Set<ExtensionCapability> = [
        .commands,
        .panels,
        .mcpTools,
        .settings,
        .servicesProvide,
        .servicesConsume,
        .companionOperations,
        .componentCustomization,
        .workspaceNavigation,
        .customMetalSurfaces,
        .hostProjectsRead,
        .hostSessionsRead,
        .hostSessionRuntimeRead,
        .hostRepositoriesRead,
        .hostProvidersRead,
        .hostAccountsPresentationRead,
        .hostEvents,
        .providerIconResolver,
        .accountIconResolver,
        .sessionIdentityRenderer,
        .themeProvider,
        .fontProvider,
        .keyValueStorage,
        .cacheStorage,
        .secrets,
        .networkClient
    ]
    /// A theme document is data in the store's own vocabulary; the manifest cap is generous
    /// beside a real document's few hundred bytes.
    static let maximumThemeBytes = 256 * 1024
    /// A theme's app-icon mark, before normalisation. Generous for a 1024² PNG with alpha, and
    /// still bounded so a package cannot ship a print-resolution asset per theme.
    static let maximumThemeIconBytes = 2 * 1024 * 1024
    /// The macOS icon canvas. A mark larger than this is downsampled rather than refused —
    /// nothing is gained by making an author re-export artwork that is merely oversized.
    static let maximumThemeIconPixels = 1024
    /// A text face with broad coverage runs to a few megabytes; CJK families run larger.
    static let maximumFontBytes = 16 * 1024 * 1024
    static let maximumLocalizationBytes = 512 * 1024
    static let maximumLocalizationEntries = 4_096
    static let maximumLocalizedStringLength = 10_000

    static func inspect(at directory: URL) throws -> ThreadingExtensionBundle {
        let root = directory.standardizedFileURL.resolvingSymlinksInPath()
        let manifestURL = root.appendingPathComponent(manifestName, isDirectory: false)

        let manifest: ExtensionManifest
        do {
            let handle = try FileHandle(forReadingFrom: manifestURL)
            defer { try? handle.close() }
            let data = try handle.read(upToCount: maximumManifestBytes + 1) ?? Data()
            guard data.count <= maximumManifestBytes else {
                throw ExtensionBundleError.manifestTooLarge(maximum: maximumManifestBytes)
            }
            // The format version is read on its own, before the manifest it describes.
            // A future format may not decode into today's type at all, and reporting that as
            // "unreadable" would blame the file for being new. Asking this one question first
            // is what lets the failure say which side is out of date.
            try checkFormatVersion(in: data)
            manifest = try JSONDecoder().decode(ExtensionManifest.self, from: data)
            try manifest.validate()
        } catch let error as ExtensionBundleError {
            throw error
        } catch let error as ExtensionValidationError {
            throw ExtensionBundleError.manifestInvalid(error.description)
        } catch {
            throw ExtensionBundleError.manifestUnreadable(error.localizedDescription)
        }

        let capabilitiesForRuntime = manifest.runtime == .webAssembly
            ? ThreadingExtensionAPI.safeCapabilities
            : supportedCapabilities
        let unsupported = manifest.capabilities
            .subtracting(capabilitiesForRuntime)
            .map(\.rawValue)
            .sorted()
        guard unsupported.isEmpty else {
            throw ExtensionBundleError.unsupportedCapabilities(unsupported)
        }
        let unsupportedCompanionCapabilities = manifest.companions
            .flatMap { companion in
                companion.capabilities
                    .subtracting(ThreadingCompanionAPI.supportedCapabilities)
                    .map { "\(companion.id):\($0.rawValue)" }
            }
            .sorted()
        guard unsupportedCompanionCapabilities.isEmpty else {
            throw ExtensionBundleError.unsupportedCompanionCapabilities(
                unsupportedCompanionCapabilities
            )
        }

        let executable = root
            .appendingPathComponent(manifest.executable, isDirectory: false)
            .standardizedFileURL
            .resolvingSymlinksInPath()
        guard isInside(executable, root: root) else {
            throw ExtensionBundleError.executableEscapesBundle
        }

        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(
            atPath: executable.path,
            isDirectory: &isDirectory
        ) else {
            throw ExtensionBundleError.executableMissing(manifest.executable)
        }
        guard !isDirectory.boolValue else {
            throw ExtensionBundleError.executableNotRunnable(manifest.executable)
        }
        let sourceURL: URL?
        switch manifest.runtime {
        case .native:
            guard FileManager.default.isExecutableFile(atPath: executable.path) else {
                throw ExtensionBundleError.executableNotRunnable(manifest.executable)
            }
            sourceURL = nil
        case .webAssembly:
            guard hasWebAssemblyMagic(at: executable) else {
                throw ExtensionBundleError.webAssemblyModuleInvalid(manifest.executable)
            }
            do {
                sourceURL = try ExtensionEditableSource.inspect(inBundle: root).rootURL
            } catch {
                throw ExtensionBundleError.editableSourceInvalid(
                    (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
                )
            }
        }
        let companions = try inspectCompanions(
            manifest.companions,
            extensionIdentifier: manifest.identifier,
            root: root
        )
        let themes = try inspectThemes(
            manifest.themes,
            extensionIdentifier: manifest.identifier,
            root: root
        )
        let fonts = try inspectFonts(manifest.fonts, root: root)
        let localizations = try inspectLocalizations(manifest.localizations, root: root)

        return ThreadingExtensionBundle(
            rootURL: root,
            executableURL: executable,
            sourceURL: sourceURL,
            manifest: manifest,
            companions: companions,
            themes: themes,
            fonts: fonts,
            localizations: localizations
        )
    }

    /// Reads and validates every declared theme document. Purely data: decode, namespace the
    /// id, and hold it to the same gates a custom theme faces — a contributed theme with
    /// unreadable labels or a missing role is refused at the door, not discovered as a broken
    /// window after enabling.
    ///
    /// Internal rather than private because the **live reload** path re-runs exactly this and
    /// nothing else: `ExtensionManager.refreshContributedThemes` calls it when a watched
    /// package's theme data changes on disk, so an enabled extension can rewrite its own
    /// document — a chrome following the weather, the hour, a build's state — and the host
    /// follows through the same decode, the same validation, the same asset gates as at
    /// install. Only theme *data* reloads this way; a manifest change is an update, with the
    /// re-disclosure an update owes.
    static func inspectThemes(
        _ declarations: [ExtensionThemeContribution],
        extensionIdentifier: String,
        root: URL
    ) throws -> [ThreadingExtensionThemeDocument] {
        try declarations.map { declaration in
            let url = try resolveResource(
                declaration.resource,
                root: root,
                maximumBytes: maximumThemeBytes,
                failure: { ExtensionBundleError.themeResourceInvalid(
                    path: declaration.resource, message: $0
                ) }
            )
            let document: AppTheme
            do {
                document = try JSONDecoder().decode(AppTheme.self, from: Data(contentsOf: url))
            } catch {
                throw ExtensionBundleError.themeResourceInvalid(
                    path: declaration.resource,
                    message: "not a readable app-theme document (\(error.localizedDescription))"
                )
            }
            // The namespaced id is the host's, not the document's: whatever the file states,
            // the library sees `ext.<extension>.<contribution>` — stable across updates, and
            // never a stock or custom theme's identity.
            let theme = AppTheme(
                id: AppThemeID("ext.\(extensionIdentifier).\(declaration.id)"),
                name: document.name,
                mode: document.mode,
                summary: document.summary,
                variants: document.variants
            )
            do {
                try AppThemeEditing.validate(theme)
            } catch {
                throw ExtensionBundleError.themeResourceInvalid(
                    path: declaration.resource,
                    message: (error as? LocalizedError)?.errorDescription
                        ?? error.localizedDescription
                )
            }
            return ThreadingExtensionThemeDocument(
                contributionID: declaration.id,
                theme: theme,
                iconMark: try inspectThemeIconMark(declaration, root: root),
                sidebarAssets: try inspectSidebarAssets(
                    of: theme,
                    declaredAt: declaration.resource,
                    root: root
                )
            )
        }
    }

    /// Reads every image the theme document's own `sidebar` blocks reference.
    ///
    /// The document names package-relative paths; nothing new appears in the manifest, because
    /// the sidebar block is part of the same app-theme vocabulary the contribution already
    /// ships — the host grows a field and old packages keep validating. The gates match the
    /// icon mark's: safe relative path, byte cap, the shared ImageIO decode-and-re-encode. A
    /// referenced file that is missing or not an image fails the whole package at inspection,
    /// because a theme shipping a background the host will not draw is a disagreement its
    /// author needs to see — the same stance `inspectThemeIconMark` states.
    ///
    /// The one gate deliberately *not* applied is `fillsItsBounds`: that rule exists so a
    /// package cannot re-plate the Dock icon, and a sidebar background is an opaque rectangle
    /// by design.
    private static func inspectSidebarAssets(
        of theme: AppTheme,
        declaredAt declarationPath: String,
        root: URL
    ) throws -> [String: Data] {
        var slots: [String: SidebarAssetSlot] = [:]
        for variant in theme.variants.values {
            if let name = variant.sidebar?.background?.image?.asset {
                slots[name] = .background
            }
            if case .asset(let name) = variant.sidebar?.brand.map(\.logo) {
                // A name used for both slots keeps the background's larger pixel budget.
                if slots[name] == nil { slots[name] = .logo }
            }
        }

        var assets: [String: Data] = [:]
        for (name, slot) in slots {
            let url = try resolveResource(
                name,
                root: root,
                maximumBytes: SidebarStyleLimits.maximumImageBytes,
                failure: { ExtensionBundleError.themeResourceInvalid(path: name, message: $0) }
            )
            guard let data = try? Data(contentsOf: url),
                  let normalized = ProjectIconStore.normalizedPNGData(
                      from: data,
                      maxPixelSize: ThemeAssetDefaults.storedPixelSize(for: slot)
                  ) else {
                throw ExtensionBundleError.themeResourceInvalid(
                    path: name,
                    message: "referenced by \(declarationPath)'s sidebar block "
                        + "but not a readable image"
                )
            }
            assets[name] = normalized
        }
        return assets
    }

    /// Reads a theme's declared app-icon mark, and refuses anything that is not one.
    ///
    /// **This is the anti-impersonation gate, and it runs at inspection** — before the package
    /// is enabled, before any of its code exists as a process, and before the install
    /// disclosure is shown. A mark that fails here fails the whole package rather than
    /// degrading quietly, because a theme shipping artwork the host will not draw is a
    /// disagreement its author needs to see.
    ///
    /// Two rules. It goes through `ProjectIconStore.normalizedPNGData`, the same ImageIO gate
    /// every untrusted image in this app passes — largest frame, size-capped, re-encoded — so a
    /// malformed file, an unsupported format, or an HTML error page saved with a `.png` suffix
    /// is refused rather than handed to a drawing path. And it must **not fill its own bounds**:
    /// the host composites this on a plate of the theme's own ground, so an opaque rectangle is
    /// a tile trying to be the whole icon, which is exactly the shape a package would use to
    /// make Threading's Dock icon look like some other application's.
    private static func inspectThemeIconMark(
        _ declaration: ExtensionThemeContribution,
        root: URL
    ) throws -> Data? {
        guard let path = declaration.iconMark else { return nil }

        let url = try resolveResource(
            path,
            root: root,
            maximumBytes: maximumThemeIconBytes,
            failure: { ExtensionBundleError.themeResourceInvalid(path: path, message: $0) }
        )
        guard let data = try? Data(contentsOf: url),
              let normalized = ProjectIconStore.normalizedPNGData(
                  from: data,
                  maxPixelSize: maximumThemeIconPixels
              ),
              let image = NSImage(data: normalized) else {
            throw ExtensionBundleError.themeResourceInvalid(
                path: path, message: "not a readable image"
            )
        }
        guard !ProjectIconStore.fillsItsBounds(image) else {
            throw ExtensionBundleError.themeResourceInvalid(
                path: path,
                message: "must be a mark on a transparent background, not a filled tile — "
                    + "Threading draws the icon's plate from the theme's own ground"
            )
        }
        return normalized
    }

    /// Confirms every declared font file is present, bounded, and parses to at least one face.
    ///
    /// Parsing happens here, at inspection — the same trust posture as compiling a declared
    /// Metal shader: disclosed as part of the unsigned local import, and never reached without
    /// the manifest declaring it.
    private static func inspectFonts(
        _ declarations: [ExtensionFontContribution],
        root: URL
    ) throws -> [ThreadingExtensionFontFile] {
        try declarations.map { declaration in
            let url = try resolveResource(
                declaration.resource,
                root: root,
                maximumBytes: maximumFontBytes,
                failure: { ExtensionBundleError.fontResourceInvalid(
                    path: declaration.resource, message: $0
                ) }
            )
            let descriptors = CTFontManagerCreateFontDescriptorsFromURL(url as CFURL)
                as? [CTFontDescriptor]
            guard let descriptors, !descriptors.isEmpty else {
                throw ExtensionBundleError.fontResourceInvalid(
                    path: declaration.resource,
                    message: "not a parseable font file"
                )
            }
            let families = descriptors.compactMap {
                CTFontDescriptorCopyAttribute($0, kCTFontFamilyNameAttribute) as? String
            }
            return ThreadingExtensionFontFile(
                url: url,
                familyNames: Array(Set(families)).sorted()
            )
        }
    }

    private static func inspectLocalizations(
        _ declarations: [ExtensionLocalizationContribution],
        root: URL
    ) throws -> [ThreadingExtensionLocalizationCatalog] {
        try declarations.map { declaration in
            let url = try resolveResource(
                declaration.resource,
                root: root,
                maximumBytes: maximumLocalizationBytes,
                failure: { ExtensionBundleError.localizationResourceInvalid(
                    path: declaration.resource, message: $0
                ) }
            )
            let strings: [String: String]
            do {
                strings = try JSONDecoder().decode(
                    [String: String].self,
                    from: Data(contentsOf: url)
                )
            } catch {
                throw ExtensionBundleError.localizationResourceInvalid(
                    path: declaration.resource,
                    message: "must be a flat JSON object of string keys and values"
                )
            }
            guard strings.count <= maximumLocalizationEntries else {
                throw ExtensionBundleError.localizationResourceInvalid(
                    path: declaration.resource,
                    message: "contains more than \(maximumLocalizationEntries) strings"
                )
            }
            if let invalid = strings.first(where: {
                $0.key.isEmpty
                    || $0.key.count > maximumLocalizedStringLength
                    || $0.value.isEmpty
                    || $0.value.count > maximumLocalizedStringLength
            }) {
                throw ExtensionBundleError.localizationResourceInvalid(
                    path: declaration.resource,
                    message: "key and value for '\(invalid.key)' must contain 1–"
                        + "\(maximumLocalizedStringLength) characters"
                )
            }
            if let invalid = strings.first(where: {
                formatPlaceholders(in: $0.key) != formatPlaceholders(in: $0.value)
            }) {
                throw ExtensionBundleError.localizationResourceInvalid(
                    path: declaration.resource,
                    message: "translation for '\(invalid.key)' must preserve its printf "
                        + "placeholders in the same order"
                )
            }
            return ThreadingExtensionLocalizationCatalog(
                language: declaration.locale,
                strings: strings
            )
        }
    }

    private static func formatPlaceholders(in value: String) -> [String] {
        let pattern =
            #"%(\d+\$)?[-+ #0']*(\d+|\*)?(\.(\d+|\*))?(hh|h|ll|l|q|L|z|t|j)?[@diuoxXfFeEgGaAcCsSp%]"#
        guard let expression = try? NSRegularExpression(pattern: pattern) else {
            return []
        }
        let range = NSRange(value.startIndex..<value.endIndex, in: value)
        return expression.matches(in: value, range: range).compactMap {
            Range($0.range, in: value).map { String(value[$0]) }
        }
    }

    private static func resolveResource(
        _ relativePath: String,
        root: URL,
        maximumBytes: Int,
        failure: (String) -> ExtensionBundleError
    ) throws -> URL {
        let candidate = root.appendingPathComponent(relativePath, isDirectory: false)
            .standardizedFileURL
            .resolvingSymlinksInPath()
        guard isInside(candidate, root: root) else {
            throw failure("resolves outside the extension directory")
        }
        guard let values = try? candidate.resourceValues(
            forKeys: [.isRegularFileKey, .fileSizeKey]
        ), values.isRegularFile == true else {
            throw failure("missing or not a regular file")
        }
        guard (values.fileSize ?? Int.max) <= maximumBytes else {
            throw failure("larger than \(maximumBytes) bytes")
        }
        return candidate
    }

    /// Reads only `formatVersion`, tolerating everything else the document may contain.
    ///
    /// A manifest missing the key entirely falls through to the full decode, which reports the
    /// missing field precisely — that is a malformed manifest, not an incompatible one.
    private static func checkFormatVersion(in data: Data) throws {
        struct FormatProbe: Decodable {
            let formatVersion: Int?
        }
        guard let probe = try? JSONDecoder().decode(FormatProbe.self, from: data),
              let found = probe.formatVersion,
              found != ExtensionManifest.currentFormatVersion else {
            return
        }
        throw ExtensionBundleError.manifestFormatUnsupported(
            found: found,
            supported: ExtensionManifest.currentFormatVersion
        )
    }

    private static func isInside(_ candidate: URL, root: URL) -> Bool {
        candidate.path.hasPrefix(root.path + "/")
    }

    private static func hasWebAssemblyMagic(at url: URL) -> Bool {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return false }
        defer { try? handle.close() }
        return (try? handle.read(upToCount: 4)) == Data([0x00, 0x61, 0x73, 0x6D])
    }

    private static func inspectCompanions(
        _ declarations: [ExtensionCompanion],
        extensionIdentifier: String,
        root: URL
    ) throws -> [ThreadingExtensionCompanionBundle] {
        try declarations.map { declaration in
            let id = declaration.id
            let companionRoot = root
                .appendingPathComponent(declaration.bundlePath, isDirectory: true)
                .standardizedFileURL
                .resolvingSymlinksInPath()
            guard isInside(companionRoot, root: root) else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "its app bundle resolves outside the extension package"
                )
            }

            var isDirectory: ObjCBool = false
            guard FileManager.default.fileExists(
                atPath: companionRoot.path,
                isDirectory: &isDirectory
            ), isDirectory.boolValue else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "the app bundle does not exist at \(declaration.bundlePath)"
                )
            }

            let infoURL = companionRoot.appendingPathComponent(
                "Contents/Info.plist",
                isDirectory: false
            )
            let infoData: Data
            do {
                let handle = try FileHandle(forReadingFrom: infoURL)
                defer { try? handle.close() }
                infoData = try handle.read(upToCount: maximumCompanionInfoBytes + 1) ?? Data()
                guard infoData.count <= maximumCompanionInfoBytes else {
                    throw ExtensionBundleError.companionInvalid(
                        id: id,
                        message: "Contents/Info.plist exceeds \(maximumCompanionInfoBytes) bytes"
                    )
                }
            } catch let error as ExtensionBundleError {
                throw error
            } catch {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "Contents/Info.plist could not be read"
                )
            }

            let propertyList: [String: Any]
            do {
                let value = try PropertyListSerialization.propertyList(
                    from: infoData,
                    options: [],
                    format: nil
                )
                guard let dictionary = value as? [String: Any] else {
                    throw ExtensionBundleError.companionInvalid(
                        id: id,
                        message: "Contents/Info.plist is not a dictionary"
                    )
                }
                propertyList = dictionary
            } catch let error as ExtensionBundleError {
                throw error
            } catch {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "Contents/Info.plist is malformed"
                )
            }

            guard propertyList["CFBundlePackageType"] as? String == "APPL" else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "CFBundlePackageType must be 'APPL'"
                )
            }
            let expectedIdentifier = declaration.expectedBundleIdentifier(
                extensionIdentifier: extensionIdentifier
            )
            guard let bundleIdentifier = propertyList["CFBundleIdentifier"] as? String,
                  bundleIdentifier == expectedIdentifier else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "CFBundleIdentifier must be \(expectedIdentifier)"
                )
            }
            guard let executableName = propertyList["CFBundleExecutable"] as? String,
                  !executableName.isEmpty,
                  !executableName.contains("/"),
                  executableName != ".",
                  executableName != ".." else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "CFBundleExecutable must name one file in Contents/MacOS"
                )
            }

            let executable = companionRoot
                .appendingPathComponent(
                    "Contents/MacOS/\(executableName)",
                    isDirectory: false
                )
                .standardizedFileURL
                .resolvingSymlinksInPath()
            guard isInside(executable, root: companionRoot) else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "its executable resolves outside the companion app"
                )
            }
            var executableIsDirectory: ObjCBool = false
            guard FileManager.default.fileExists(
                atPath: executable.path,
                isDirectory: &executableIsDirectory
            ), !executableIsDirectory.boolValue,
            FileManager.default.isExecutableFile(atPath: executable.path) else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "Contents/MacOS/\(executableName) is not executable"
                )
            }
            let signature = try inspectCompanionSignature(
                at: companionRoot,
                id: id,
                expectedIdentifier: expectedIdentifier,
                capabilities: declaration.capabilities
            )

            return ThreadingExtensionCompanionBundle(
                declaration: declaration,
                bundleURL: companionRoot,
                executableURL: executable,
                bundleIdentifier: bundleIdentifier,
                signedEntitlements: signature.entitlements,
                designatedRequirementData: signature.designatedRequirementData,
                signingTeamIdentifier: signature.teamIdentifier
            )
        }
    }

    private struct CompanionSignature {
        let entitlements: Set<String>
        let designatedRequirementData: Data
        let teamIdentifier: String?
    }

    private static func inspectCompanionSignature(
        at appURL: URL,
        id: String,
        expectedIdentifier: String,
        capabilities: Set<ExtensionCompanionCapability>
    ) throws -> CompanionSignature {
        var staticCode: SecStaticCode?
        let createStatus = SecStaticCodeCreateWithPath(
            appURL as CFURL,
            SecCSFlags(),
            &staticCode
        )
        guard createStatus == errSecSuccess, let staticCode else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its code signature could not be read"
            )
        }
        let validationFlags = SecCSFlags(
            rawValue: kSecCSStrictValidate | kSecCSCheckAllArchitectures
        )
        guard SecStaticCodeCheckValidity(staticCode, validationFlags, nil) == errSecSuccess else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its code signature is invalid"
            )
        }

        var signingInformation: CFDictionary?
        let informationStatus = SecCodeCopySigningInformation(
            staticCode,
            SecCSFlags(rawValue: kSecCSSigningInformation),
            &signingInformation
        )
        guard informationStatus == errSecSuccess,
              let information = signingInformation as? [String: Any] else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its signed identity could not be inspected"
            )
        }
        guard information[kSecCodeInfoIdentifier as String] as? String
                == expectedIdentifier else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its code-signing identifier must be \(expectedIdentifier)"
            )
        }

        // CS_RUNTIME from <sys/codesign.h>. Security exposes the flags value through
        // kSecCodeInfoFlags but Darwin does not import this one constant into Swift.
        let hardenedRuntimeFlag: UInt32 = 0x0001_0000
        let codeFlags = (information[kSecCodeInfoFlags as String] as? NSNumber)?
            .uint32Value ?? 0
        guard codeFlags & hardenedRuntimeFlag != 0 else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "it must be signed with the hardened runtime"
            )
        }

        let entitlements = information[kSecCodeInfoEntitlementsDict as String]
            as? [String: Any] ?? [:]
        try validateCompanionEntitlements(
            entitlements,
            id: id,
            capabilities: capabilities
        )

        var designatedRequirement: SecRequirement?
        guard SecCodeCopyDesignatedRequirement(
            staticCode,
            SecCSFlags(),
            &designatedRequirement
        ) == errSecSuccess, let designatedRequirement else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its designated code requirement could not be read"
            )
        }
        var requirementData: CFData?
        guard SecRequirementCopyData(
            designatedRequirement,
            SecCSFlags(),
            &requirementData
        ) == errSecSuccess, let requirementData else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "its designated code requirement could not be serialized"
            )
        }

        return CompanionSignature(
            entitlements: Set(entitlements.keys),
            designatedRequirementData: requirementData as Data,
            teamIdentifier: information[kSecCodeInfoTeamIdentifier as String] as? String
        )
    }

    /// Re-inspects a nested app immediately before launch and applies the requirement captured
    /// when the installed package entered the current manager generation.
    ///
    /// A path check performed at import is not evidence about the bytes at exec time. The fresh
    /// inspection repeats bundle, executable, signature, hardened-runtime, sandbox, and
    /// entitlement validation; the pinned requirement then prevents a replacement signed by a
    /// different author (or different ad-hoc code directory) from racing into the launch.
    static func revalidateCompanionForLaunch(
        _ pinned: ThreadingExtensionCompanionBundle,
        in pinnedBundle: ThreadingExtensionBundle
    ) throws -> ThreadingExtensionCompanionBundle {
        let freshBundle = try inspect(at: pinnedBundle.rootURL)
        guard freshBundle.manifest.identifier == pinnedBundle.manifest.identifier,
              let fresh = freshBundle.companions.first(where: {
                  $0.declaration.id == pinned.declaration.id
              }),
              fresh.declaration == pinned.declaration,
              fresh.bundleURL == pinned.bundleURL,
              fresh.executableURL == pinned.executableURL else {
            throw ExtensionBundleError.companionInvalid(
                id: pinned.declaration.id,
                message: "its declaration or executable changed before launch"
            )
        }

        var requirement: SecRequirement?
        let requirementStatus = SecRequirementCreateWithData(
            pinned.designatedRequirementData as CFData,
            SecCSFlags(),
            &requirement
        )
        guard requirementStatus == errSecSuccess, let requirement else {
            throw ExtensionBundleError.companionInvalid(
                id: pinned.declaration.id,
                message: "its pinned code requirement could not be restored"
            )
        }

        var staticCode: SecStaticCode?
        guard SecStaticCodeCreateWithPath(
            fresh.bundleURL as CFURL,
            SecCSFlags(),
            &staticCode
        ) == errSecSuccess, let staticCode else {
            throw ExtensionBundleError.companionInvalid(
                id: pinned.declaration.id,
                message: "its code signature could not be read immediately before launch"
            )
        }
        let flags = SecCSFlags(rawValue: kSecCSStrictValidate | kSecCSCheckAllArchitectures)
        guard SecStaticCodeCheckValidity(staticCode, flags, requirement) == errSecSuccess else {
            throw ExtensionBundleError.companionInvalid(
                id: pinned.declaration.id,
                message: "it no longer satisfies the code requirement approved for this generation"
            )
        }
        return fresh
    }

    private static func validateCompanionEntitlements(
        _ entitlements: [String: Any],
        id: String,
        capabilities: Set<ExtensionCompanionCapability>
    ) throws {
        func enabled(_ key: String) -> Bool {
            (entitlements[key] as? Bool) == true
                || (entitlements[key] as? NSNumber)?.boolValue == true
        }
        guard enabled("com.apple.security.app-sandbox") else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "it must opt into App Sandbox"
            )
        }

        let mappings: [(ExtensionCompanionCapability, String)] = [
            (.networkClient, "com.apple.security.network.client"),
            (.networkListen, "com.apple.security.network.server"),
            (.appleEvents, "com.apple.security.automation.apple-events")
        ]
        for (capability, entitlement) in mappings {
            let requested = capabilities.contains(capability)
            guard requested == enabled(entitlement) else {
                let message = requested
                    ? "\(capability.rawValue) requires signed entitlement \(entitlement)"
                    : "signed entitlement \(entitlement) was not declared as a companion capability"
                throw ExtensionBundleError.companionInvalid(id: id, message: message)
            }
        }

        let readOnly = "com.apple.security.files.user-selected.read-only"
        let readWrite = "com.apple.security.files.user-selected.read-write"
        let requestsRead = capabilities.contains(.userSelectedFilesRead)
        let requestsWrite = capabilities.contains(.userSelectedFilesWrite)
        if requestsWrite {
            guard enabled(readWrite), !enabled(readOnly) else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "\(ExtensionCompanionCapability.userSelectedFilesWrite.rawValue) "
                        + "requires only signed entitlement \(readWrite)"
                )
            }
        } else if requestsRead {
            guard enabled(readOnly), !enabled(readWrite) else {
                throw ExtensionBundleError.companionInvalid(
                    id: id,
                    message: "\(ExtensionCompanionCapability.userSelectedFilesRead.rawValue) "
                        + "requires only signed entitlement \(readOnly)"
                )
            }
        } else if enabled(readOnly) || enabled(readWrite) {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "signed user-selected file authority was not declared"
            )
        }

        let understoodSecurityEntitlements: Set<String> = [
            "com.apple.security.app-sandbox",
            "com.apple.security.get-task-allow",
            "com.apple.security.network.client",
            "com.apple.security.network.server",
            "com.apple.security.automation.apple-events",
            readOnly,
            readWrite
        ]
        let undeclaredSecurityEntitlements = entitlements.keys
            .filter {
                $0.hasPrefix("com.apple.security.")
                    && !understoodSecurityEntitlements.contains($0)
            }
            .sorted()
        guard undeclaredSecurityEntitlements.isEmpty else {
            throw ExtensionBundleError.companionInvalid(
                id: id,
                message: "it carries unsupported signed entitlements: "
                    + undeclaredSecurityEntitlements.joined(separator: ", ")
            )
        }
    }
}

/// The deliberately small first process protocol.
///
/// The executable receives `--threading-register`, writes exactly one
/// `ExtensionRegistration` JSON value to stdout, then exits. Interactive actions and a
/// persistent process are a later protocol version; this handshake lets us exercise discovery,
/// execution, validation, and rendering without prematurely inventing that larger transport.
enum ExtensionRegistrationLoader {
    static let defaultTimeout: TimeInterval = 3
    static let maximumOutputBytes = 1024 * 1024

    /// Blocks while the extension registers. Production callers must invoke this off the main
    /// thread; keeping the primitive synchronous makes its timeout and process lifetime explicit.
    static func load(
        from bundle: ThreadingExtensionBundle,
        policy: ExtensionLaunchPolicy = RuntimeSelectingLaunchPolicy(),
        timeout: TimeInterval = defaultTimeout,
        maximumOutput: Int = maximumOutputBytes
    ) throws -> ExtensionRegistration {
        let stdout = Pipe()
        let stderr = Pipe()
        let interruption = Interruption()
        let stdoutCapture = PipeCapture(maximum: maximumOutput)
        let stderrCapture = PipeCapture(maximum: maximumOutput)
        let drains = DispatchGroup()

        let child: ExtensionChildProcess
        do {
            child = try policy.spawn(
                ExtensionLaunchRequest(
                    bundle: bundle,
                    arguments: ["--threading-register"],
                    standardInput: .nullDevice,
                    standardOutput: .pipe(stdout),
                    standardError: .pipe(stderr)
                )
            )
        } catch {
            throw ExtensionBundleError.launchFailed(error.localizedDescription)
        }

        @Sendable func interrupt(_ reason: Interruption.Reason) {
            guard interruption.record(reason) else { return }
            guard child.isRunning else { return }
            child.terminate()
            DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + 0.25) {
                child.kill()
            }
        }

        drains.enter()
        DispatchQueue.global(qos: .userInitiated).async {
            stdoutCapture.drain(stdout.fileHandleForReading) {
                interrupt(.oversized)
            }
            drains.leave()
        }

        drains.enter()
        DispatchQueue.global(qos: .userInitiated).async {
            stderrCapture.drain(stderr.fileHandleForReading) {
                interrupt(.oversized)
            }
            drains.leave()
        }

        let timeoutItem = DispatchWorkItem {
            guard child.isRunning else { return }
            interrupt(.timedOut)
        }
        DispatchQueue.global(qos: .userInitiated).asyncAfter(
            deadline: .now() + timeout,
            execute: timeoutItem
        )

        child.waitUntilExit()
        timeoutItem.cancel()
        drains.wait()

        switch interruption.reason {
        case .timedOut:
            throw ExtensionBundleError.timedOut
        case .oversized:
            throw ExtensionBundleError.outputTooLarge(maximum: maximumOutput)
        case nil:
            break
        }

        let errorMessage = String(decoding: stderrCapture.data, as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard child.terminationStatus == 0 else {
            throw ExtensionBundleError.processFailed(
                status: child.terminationStatus,
                message: errorMessage
            )
        }

        do {
            let registration = try JSONDecoder().decode(
                ExtensionRegistration.self,
                from: stdoutCapture.data
            )
            try registration.validate(for: bundle.manifest)
            return registration
        } catch {
            let message = (error as? ExtensionValidationError)?.description
                ?? error.localizedDescription
            throw ExtensionBundleError.invalidRegistration(message)
        }
    }

    private final class PipeCapture: @unchecked Sendable {
        private let maximum: Int
        private(set) var data = Data()

        init(maximum: Int) {
            self.maximum = maximum
        }

        func drain(_ handle: FileHandle, onOversize: () -> Void) {
            while true {
                let chunk = handle.availableData
                if chunk.isEmpty { return }

                let remaining = max(0, maximum - data.count)
                data.append(chunk.prefix(remaining))
                if chunk.count > remaining {
                    onOversize()
                    _ = handle.readDataToEndOfFile()
                    return
                }
            }
        }
    }

    private final class Interruption: @unchecked Sendable {
        enum Reason {
            case timedOut
            case oversized
        }

        private let lock = NSLock()
        private var value: Reason?

        @discardableResult
        func record(_ reason: Reason) -> Bool {
            lock.lock()
            defer { lock.unlock() }
            guard value == nil else { return false }
            value = reason
            return true
        }

        var reason: Reason? {
            lock.lock()
            defer { lock.unlock() }
            return value
        }
    }
}
