// Generated by scripts/publish_remote_components.sh. Do not edit by hand.
//
// Rewritten wholesale each time the Linux components are published: the script builds them, hashes
// what it built, uploads the assets and writes the digests it measured here.

import Foundation

/// The components this build knows how to fetch, and where they live.
///
/// **Generated, not written by hand.** `scripts/publish_remote_components.sh` builds the Linux
/// binaries, uploads them to their own release and rewrites this file with the digests it measured.
/// Compiling the digests in is what makes the download safe to do at all: the app never trusts the
/// bytes it receives, only the bytes it was built expecting.
///
/// Empty in a build that has published none, which is not a failure of the download — it is a build
/// that cannot set up a host, and says so in those words.
enum RemoteHostComponentManifest {

    /// The release tag carrying these assets.
    static let release = ""

    /// Where the assets are, one directory for the release.
    static let baseURL = "https://github.com/everlof/threading/releases/download/"

    static let components: [RemoteHostComponent] = []

    static func component(
        _ kind: RemoteHostBinaryKind,
        for architecture: RemoteHostArchitecture
    ) -> RemoteHostComponent? {
        components.first { $0.kind == kind && $0.architecture == architecture }
    }

    static func url(for component: RemoteHostComponent) -> URL? {
        URL(string: baseURL + release + "/" + component.assetName)
    }

    /// What one host costs to set up, for the sentence that asks.
    static func downloadByteCount(for architecture: RemoteHostArchitecture) -> Int {
        components.filter { $0.architecture == architecture }.reduce(0) { $0 + $1.assetByteCount }
    }
}
